# Generated by Django 4.1.4 on 2022-12-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dec', models.TextField()),
                ('Year', models.IntegerField()),
                ('Img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
